home:
    path:  /
    defaults: { _controller: AppBundle:Default:index }

app_directory_list:
    path:  /directory/{directory}
    defaults: { _controller: AppBundle:Directory:list, directory: null}

app_directory_edit:
    path:  /directory/edit/{directory}
    defaults: { _controller: AppBundle:Directory:edit}

app_file_download:
    path:  /file/get/{file}
    defaults: { _controller: AppBundle:File:get}

app_file_edit:
    path:  /file/edit/{file}
    defaults: { _controller: AppBundle:File:edit}